FROM rockylinux:8

ENV container docker
STOPSIGNAL SIGRTMIN+3

RUN dnf -y update && dnf -y install glibc-langpack-en epel-release dnf-plugins-core
RUN dnf config-manager --set-enabled powertools

RUN dnf -y groupinstall "Development Tools"
RUN dnf -y install sssd-client  sudo  perl-interpreter openssh-clients yum-utils python3-gitlab
RUN alternatives --set python /usr/bin/python3

# disable kdump service as it is throwing an error on some hosts 
# (e.g. hbfade)
RUN systemctl disable kdump 

# copy repo information which is created
# by gitlab-ci in an earlier stage
COPY gem-rtsw.repo /etc/yum.repos.d/

# copy mock configuration which is created
# by gitlab-ci in an earlier stage
COPY gem-rtsw.cfg /etc/mock/
#COPY gem-rtsw-common.tpl /etc/mock/templates/

# copy tito releaser.conf to global directory
# to be used with appropriate gemini-ade scripts
# for 'tito release' command
## ommit copying it to prevent against releasing manually to repo
#COPY releasers.conf /gem_base/usr/share/tito/common/

RUN dnf config-manager --enable gem-rtsw-*
RUN dnf makecache || echo "!! failed to make cache, is the repository initialized already? !!"

# install all available packages from the gen-rtsw repos
RUN repoquery --disablerepo="*" --enablerepo="gem-rtsw-*" --available > packagelist.txt
RUN xargs dnf -y install --skip-broken < packagelist.txt || printf '!! failed to install package !! \n\
Is it deployed to the RPM repository already?'

RUN dnf clean all

# copy branch name to be used to build
# container. This is important for BASE_CONTAINERs
# namespaces being based on other project branches
COPY container_project_branch.cfg /gem_base/etc/

CMD ["/sbin/init"]

